export const DISPLAY_WIDTH = 488;
export const DISPLAY_VERTICAL_DIVISION = 100;
export const DISPLAY_HORIZONTAL_POSITION = [0, 144, 408];
export const DISPLAY_HORIZONTAL_DIVISION = [80, 200, 80];
export const DISPLAY_HORIZONTAL_COLORS = ['#F2C50D', '#0DF2C9', '#FF6E2B'];
export const DISPLAY_DELAY_UNIT = 2;
